global:
  namespace: actions-runner

replicaCount: 1

image:
  repository: myoung34/github-runner
  tag: "latest"
  pullPolicy: Always

github:
  repoUrl: "https://github.com/iitssasha/foodgram-st"

resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"

persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: ""

dind:
  enabled: true
  image: docker:24-dind
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
