apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen {{ .Values.config.port }};
        root {{ .Values.config.paths.static }};
        index index.html;
    
        location / {
            try_files $uri /index.html;
        }
    
        location /media/ {
          alias {{ .Values.config.paths.media }}/;
          expires 30d;
        }

        location /static/ {
            root {{ .Values.config.paths.static }};
            expires 1y;
            add_header Cache-Control "public";
        }
    
        location /backend_static/ {
            alias {{ .Values.config.paths.backend_static }}/;
            expires 1y;
            add_header Cache-Control "public";
        }
    
        location {{ .Values.config.locations.api }} {
            proxy_pass http://{{ .Values.config.upstreams.backend.service }}:{{ .Values.config.upstreams.backend.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    
        location {{ .Values.config.locations.admin }} {
          proxy_pass http://{{ .Values.config.upstreams.backend.service }}:{{ .Values.config.upstreams.backend.port }}{{ .Values.config.locations.admin }};
          proxy_set_header Host $host;
        }
    
        location {{ .Values.config.locations.rabbitmq }} {
          proxy_pass http://{{ .Values.config.upstreams.backend.service }}:{{ .Values.config.upstreams.backend.port }}{{ .Values.config.locations.rabbitmq }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

    
        location {{ .Values.config.locations.websocket }} {
          proxy_pass http://{{ .Values.config.upstreams.websocket.service }}:{{ .Values.config.upstreams.websocket.port }};
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
        }
    }