apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: {{ .Values.global.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"