apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.postgresql.primary.service.port }}
      targetPort: 5432
  selector:
    app: postgres