apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
  selector:
    app: django