apiVersion: batch/v1
kind: Job
metadata:
  name: collectstatic-job
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: collectstatic
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: backend-static
              mountPath: /app/static
          envFrom:
            - secretRef:
                name: db-secrets
            - configMapRef:
                name: backend-config
      volumes:
        - name: backend-static
          persistentVolumeClaim:
            claimName: static-pvc
