apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "celery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
    spec:
      containers:
        - name: {{ .Values.global.name }}
          image: {{ include "celery.backendImage" . | quote }}
          command: ["celery", "-A", "foodgram", "worker", "--loglevel=info"]
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap }}
            - secretRef:
                name: {{ .Values.secret }}
