apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.db.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}