apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}