apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  CELERY_BROKER_URL: amqp://{{ .Values.celery.broker.username }}:{{ .Values.celery.broker.password }}@{{ .Values.celery.broker.host }}:{{ .Values.celery.broker.port }}//