apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.db.size }}
  accessModes:
    - {{ .Values.persistence.db.accessMode }}
  hostPath:
    path: "/data/db"