apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.primary.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.primary.service.port }}
      targetPort: 5432
  selector:
    app: {{ .Values.primary.service.name }}