apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jobs.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ index (index (.Values.werf | default dict) "image" | default dict) "backend" | default (printf "%s:%s" .Values.global.image.backend.repository .Values.global.image.backend.tag) | quote }}
          command: ["python", "manage.py", "migrate"]
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.auth.password | quote }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.name }}
            - secretRef:
                name: {{ .Values.config.secret }}
