apiVersion: batch/v1
kind: Job
metadata:
  name: collectstatic-job
  namespace: foodgram
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: collectstatic
          image: iitssasha/foodgram:latest
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
            - secretRef:
                name: db-secrets
            - configMapRef:
                name: backend-config
