global:
  namespace: foodgram
  name: flower
  svcName: flower-ui
  environment: "development"

replicaCount: 1

env:
  port: 5555

configMap: backend-config
secret: app-env

image:
  repository: iitssasha/foodgram
  tag: "latest"
